"use client";
import React from "react";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";
import { Bar } from "react-chartjs-2";
// import {
//   ImageSizeObjectKeyType,
//   SizeBasedAnalysisData,
// } from "@/utils/helpers/sizeBitsObject";
import "./temp.css";
ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend
);

export const options = {
  indexAxis: "y" as const,
  elements: {
    bar: {
      borderWidth: 2,
    },
  },
  responsive: true,
  plugins: {
    legend: {
      position: "top" as const,
    },
    title: {
      display: true,
      text: "Tenders Generated By Month",
    },
  },
};
export function BarChart({
  labels,
  pending,
  done,
}: {
  labels: string[];
  pending: number[];
  done: number[];
}) {
  const data = {
    labels,
    datasets: [
      {
        label: "Tenders Pending",
        data: pending.map((i) => -1 * i),
        borderColor: "rgb(255, 99, 132)",
        backgroundColor: "rgba(255, 99, 132, 0.5)",
      },
      {
        label: "Tenders Sufficed",
        data: done.map((i) => i),

        borderColor: "rgb(53, 162, 235)",
        backgroundColor: "rgba(53, 162, 235, 0.5)",
      },
      {
        label: "Tenders Total",
        data: pending.map((value, index) => value + done[index]),

        borderColor: "rgba(19, 106, 48, 0.5)",
        backgroundColor: "rgb(53, 235, 141)",
      },
    ],
  };

  return <Bar className="" options={options} data={data} />;
}
